#!/bin/bash

### BEGIN INIT INFO
# Provides:          bosixnet-daemon
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts bosixnet_daemon
# Description:       starts script which check ipv6 address each N minutes
### END INIT INFO

# Author: Boris Pek
# Last updated: 2014-02-04

NAME=bosixnet_daemon
DESC="BOSixNet daemon"
DAEMON=/usr/lib/bosixnet/daemon_launcher
DAEMON_OPTS=
SCRIPT=bosixnet-daemon
PIDFILE=/var/run/${NAME}.pid


[ -x ${DAEMON} ] || exit 0

. /lib/lsb/init-functions

set -e

check_start() {
    set +e
    DAEMON_PID="$(pidof -x ${NAME})"
    if [ ! -z "${DAEMON_PID}" ]; then
        log_end_msg $?
        exit 0
    fi
    set -e
}

check_stop() {
    set +e
    DAEMON_PID="$(pidof -x ${NAME})"
    if [ ! -z "${DAEMON_PID}" ]; then
        killall -9 "${NAME}" >/dev/null 2>/dev/null
        sleep 1
    fi
    set -e
}

start() {
    check_start
    start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
        --exec "${DAEMON}" --oknodo -- ${DAEMON_OPTS}
}

stop() {
    start-stop-daemon --stop --quiet --pidfile "${PIDFILE}" \
        --exec "${DAEMON}" --oknodo --retry 5
    sleep 1
    check_stop
}

case "$1" in
    start)
        log_daemon_msg "Starting ${DESC}" "${NAME}"
        start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping ${DESC}" "${NAME}"
        stop
        log_end_msg $?
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting ${DESC}" "${NAME}"
        stop
        sleep 1
        start
        log_end_msg $?
        ;;
    status)
        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" && exit 0 || exit $?
        ;;
    install)
        cp -f ${0} /etc/init.d/${SCRIPT}
        insserv bosixnet-webui
        ;;
    remove)
        rm -f /etc/rc*.d/*${SCRIPT}*
        rm -f /etc/init.d/${SCRIPT}
        ;;
    *)
        echo "Usage: /etc/init.d/${SCRIPT} {start|stop|restart|force-reload|status|install|remove}" >&2
        exit 1
        ;;
esac

exit 0

