#!/bin/sh

# Config file
CONF_FILE="/etc/bosixnet/bosixnet-daemon.conf"

# Period of updating IPv6 address and /etc/hosts file [seconds]:
UPD_PERIOD=300

# Directory with auxiliary scripts:
DIR_UTIL="/usr/lib/bosixnet"

# Read settings from config file if it exists
[ -e "${CONF_FILE}" ] && . "${CONF_FILE}"


# Check command line options
if [ "${1}" = "-h" -o "${1}" = "--help" ]; then
    echo "Usage: bosixnet_daemon [options]

This shell script periodically sends information about current IPv6 address to
remote servers and updates local /etc/hosts file based on data received from
these remote servers. It is expected that bosixnet-webui is launched on these
remote servers, but it is not mandatory.

Generic options:
  -h, --help     show help and exit
  -v, --version  show version and exit

Settings are in config file: ${CONF_FILE}"
    exit 0
elif [ "${1}" = "-v" -o "${1}" = "--version" ]; then
    echo "Last updated: 2016-10-19"
    exit 0
fi

# Infinite cycle for periodical updates
while [ 1 ]; do
    "${DIR_UTIL}/update_address" &>/dev/null
    "${DIR_UTIL}/update_hosts"   &>/dev/null
    sleep ${UPD_PERIOD}
done

