#!/bin/sh

# Config file
CONF_FILE="/etc/bosixnet/bosixnet-daemon.conf"

# Default host name
HOST_NAME="$(uname -n)"

# Default web-site URL
URL="http://ipv6.example.com/bosixnet"

# Read settings from config file if it exists
[ -e "${CONF_FILE}" ] && . "${CONF_FILE}"


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

IPv6_INFO="$(ifconfig | grep 'inet6 addr:' | grep 'Scope:Global')"
IPv6_CUR=$(echo "${IPv6_INFO}" | sed -e "s|^.*inet6 addr:\ \(.*\)/[0-9]*\ Scope:Global$|\1|" | tail -n1)

if [ ! -z "${IPv6_CUR}" ]; then
    for DEST in ${URL} ; do
        LINK="${DEST}/${HOST_NAME}"
        IPv6_OLD="$(curl ${LINK} 2>/dev/null)"
        if [ "${IPv6_OLD}" != "${IPv6_CUR}" ]; then
            curl "${LINK}?update=${IPv6_CUR}" 2>/dev/null >/dev/null
        fi
    done
fi
